"""relationships_and_constraints

Revision ID: 19940b0ba16f
Revises: bd4bb62286cc
Create Date: 2026-06-20 20:42:07.675914

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '19940b0ba16f'
down_revision: Union[str, None] = 'bd4bb62286cc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('audit_logs', 'user_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('fraud_events', 'transaction_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('investigations', 'fraud_event_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('users', 'email',
               existing_type=sa.VARCHAR(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'email',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('investigations', 'fraud_event_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('fraud_events', 'transaction_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('audit_logs', 'user_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###
